name: Forest app CI/CD aws ECR ECS
run-name: Testing and Deploying Spring Boot App to AWS ECR ECS
on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SPRING_DATASOURCE_URL: ${{ secrets.DATABASE_URL }}
      SERVER_PORT: 5000
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: sudo chmod +x ./gradlew test